// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuylaiuztrcwflgitagm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1eWxhaXV6dHJjd2ZsZ2l0YWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NDAwNDksImV4cCI6MjA2NDAxNjA0OX0.nPk2s3ZFUpvmdwtwgftNfr-7C8jIAmwxec2T8O8VnR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);